### ISSUE TITLE
ng2-img-max

### ISSUE THREAD

**Issue by dfa1234** [bergben/bergben#1]
Hi @bergben, I can't add issues on https://github.com/bergben/ng2-img-max because its archived, so I post here (you can delete after)
I wanted to contact you for sharing the repo with you, I think I can help to maintain it.
You can write me here or here my mail dfaure123@gmail.com

**Comment by bergben** [comment]
Hi @dfa1234 

Sounds great! 
I unarchived the repo and added you as a collaborator. Feel free to send PRs to get the repo up to date. If that works I'll make you an owner and will make sure you get npm access etc. 

Let's move this conversation here: https://github.com/bergben/ng2-img-max/issues/55
